### ISSUE TITLE
Client np.argmax returns 0 when it shouldn't

### ISSUE THREAD

**Issue by Shellcat-Zero** [MtDersvan/tf_playground#5] opened 2017-09-19 19:01 UTC
I was having problems always getting 0 as the prediction for my model output, then upon inspecting the TensorProto objects that are returned, noticed that it wasn't actually selecting the label with the highest probability.  Is there a better way to parse the probabilities and labels (classes) from the TensorProto objects?  I just printed them out to view their entire contents:
```
print('True label: ' + str(label))
print('Prediction: ' + str(prediction))
print('Prediction: ' + str(np.argmax(prediction)))
print('classes: ' + str(classes))
```
Then showing some of the errors I noticed (out of thousands of tests submitted):
```
True label: 1
Prediction: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 2
  }
}
float_val: 1.30707711321e-08
float_val: 1.0

Prediction: 0
classes: dtype: DT_STRING
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 2
  }
}
string_val: "0"
string_val: "1"
```
And,
```
True label: 1
Prediction: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 2
  }
}
float_val: 8.95097286957e-07
float_val: 0.999999046326

Prediction: 0
classes: dtype: DT_STRING
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 2
  }
}
string_val: "0"
string_val: "1"
```
Some correctly selected labels appear as thus,
```
True label: 0
Prediction: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 2
  }
}
float_val: 0.983799099922
float_val: 0.0162008889019

Prediction: 0
classes: dtype: DT_STRING
tensor_shape {
  dim {
    size: 1
  }
  dim {
    size: 2
  }
}
string_val: "0"
string_val: "1"
```

**Comment by MtDersvan** [comment] 2017-09-20 17:10
@Shellcat-Zero Does your `prediction` looks like this:
```
prediction = result_future.result().outputs['scores']
```
or
```
prediction = result_future.result().outputs['scores'].float_val
```
?
I feel the problem is that `np.argmax(prediction)` might always output `0` when `prediction` is not an array of `float_val`.
My suggestion is try and experiment with the `outputs` proto, and extract an actual array from it.

**Comment by nitinsurya** [comment] 2017-11-08 17:26
I faced a similar issue. To address this, I used '.float_val'. This would be required for models built using default wide and deep model settings for classification.

**Comment by MtDersvan** [comment] 2017-11-16 06:46
Fixed in https://github.com/MtDersvan/tf_playground/pull/8

**Closed by MtDersvan** 2017-11-16 06:46 UTC
