### ISSUE TITLE
Query Wide & Deep Model with saved_model_cli

### ISSUE THREAD

**Issue by Shellcat-Zero** [MtDersvan/tf_playground#3] opened 2017-09-12 20:41 UTC
Thanks for you work on this!

Can you show how someone could query this SavedModel with the saved_model_cli tool?  My attempts at querying the model with your feature dict have all failed so far.

saved_model_cli documentation: https://www.tensorflow.org/programmers_guide/saved_model#run_command

**Comment by MtDersvan** [comment] 2017-09-13 17:44
Of course!
How were you sending your requests?
Because the input is a serialized tf.Example you'll need to convert a feature_dict into a serialized proto tensor, something like this:
```
import tensorflow as tf

def _float_feature(value):
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _bytes_feature(value):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

feature_dict = {'age': _float_feature(value=25),
                'capital_gain': _float_feature(value=0),
                'capital_loss': _float_feature(value=0),
                'education': _bytes_feature(value='11th'.encode()),
                'education_num': _float_feature(value=7),
                'gender': _bytes_feature(value='Male'.encode()),
                'hours_per_week': _float_feature(value=40),
                'native_country': _bytes_feature(value='United-States'.encode()),
                'occupation': _bytes_feature(value='Machine-op-inspct'.encode()),
                'relationship': _bytes_feature(value='Own-child'.encode()),
                'workclass': _bytes_feature(value='Private'.encode())}

example = tf.train.Example(features=tf.train.Features(feature=feature_dict))

serialized = example.SerializeToString()

serialized_proto = tf.contrib.util.make_tensor_proto(serialized, shape=[1])

serialized_proto_handle = serialized_proto.string_val
```

This `serialized_proto_handle` should look like this:
```
[b'\n\xaa\x02\n\x1a\n\x0ehours_per_week\x12\x08\x12\x06\n\x04\x00\x00 B\n\x1d\n\x0crelationship\x12\r\n\x0b\n\tOwn-child\n\x19\n\reducation_num\x12\x08\x12\x06\n\x04\x00\x00\xe0@\n#\n\noccupation\x12\x15\n\x13\n\x11Machine-op-inspct\n\x18\n\x0ccapital_gain\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x18\n\x0ccapital_loss\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x15\n\teducation\x12\x08\n\x06\n\x0411th\n\x0f\n\x03age\x12\x08\x12\x06\n\x04\x00\x00\xc8A\n#\n\x0enative_country\x12\x11\n\x0f\n\rUnited-States\n\x18\n\tworkclass\x12\x0b\n\t\n\x07Private\n\x12\n\x06gender\x12\x08\n\x06\n\x04Male']
```
So this can be done separately, e.g. in an ipython or a python script.
You can either dump it into a file (pickle, .npy, .npz) or shoot it up straight from a console:
```
saved_model_cli run --dir ./wide_and_deep_tutorial/serving_savemodel/${MODEL_DIR} \
--tag_set serve --signature_def serving_default \
--input_exprs "inputs=[b'\n\xaa\x02\n\x1a\n\x0ehours_per_week\x12\x08\x12\x06\n\x04\x00\x00 B\n\x1d\n\x0crelationship\x12\r\n\x0b\n\tOwn-child\n\x19\n\reducation_num\x12\x08\x12\x06\n\x04\x00\x00\xe0@\n#\n\noccupation\x12\x15\n\x13\n\x11Machine-op-inspct\n\x18\n\x0ccapital_gain\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x18\n\x0ccapital_loss\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x15\n\teducation\x12\x08\n\x06\n\x0411th\n\x0f\n\x03age\x12\x08\x12\x06\n\x04\x00\x00\xc8A\n#\n\x0enative_country\x12\x11\n\x0f\n\rUnited-States\n\x18\n\tworkclass\x12\x0b\n\t\n\x07Private\n\x12\n\x06gender\x12\x08\n\x06\n\x04Male']"
```

```
Result for output key classes:
[[b'0' b'1']]
Result for output key scores:
[[ 0.85787761  0.14212234]]
```

Hope this helps!

**Comment by Shellcat-Zero** [comment] 2017-09-13 22:24
Thanks, it works!

**Comment by Shellcat-Zero** [comment] 2017-09-13 22:27
I was curious if these estimators require the SavedModel to work this way taking a single string input, or if the SavedModel can be defined to accept all of the different variables individually.

**Comment by MtDersvan** [comment] 2017-09-13 22:35
I think it directly depends on the input function that you specified during SaveModel export (`export_input_fn` in the tutorial). But you can define any input if you'll find out how. Here is a related issue that you might be interested https://github.com/tensorflow/tensorflow/issues/12367.
I found that in a production it is very useful to have a single serialized input (makes it clean and easy to maintain between different versions), but I agree, obviously it looks very ugly when used with `saved_model_cli`.)

**Comment by Shellcat-Zero** [comment] 2017-09-13 23:14
Ah, that's informative.

Perhaps I am going about this the wrong way.  I wanted to automate testing over hundreds or thousands of data points with the model, making changes to the data payloads and then testing again as necessary, but I didn't want to have to do "bazel build ..." on the client for frequent changes to the data payloads so that's why I'm using the saved_model_cli here.  Ideally I would do this all within python rather than having to invoke the cli.  Is there any better alternative than invoking the cli from a python subprocess?

**Comment by MtDersvan** [comment] 2017-09-13 23:36
You don't want to do `bazel build .../${DIR}:your_client`?
I think bazel builds dependencies, but links `your_client.py`, so it will use the latest changes to `your_client.py` when invoked (you can directly change *.py before every run).

**Comment by Shellcat-Zero** [comment] 2017-09-13 23:56
Ah, thanks, that clears things up.  I'll use the client then.

**Comment by QaisarRajput** [comment] 2017-09-14 10:52
my output of `serialized_proto_handle` doesn't look like yours. when i print it it shows a `<google.protobuf.pyext._message.RepeatedScalarContainer object at 0x7f9767d07490>`. which is a object. Please help!

**Comment by MtDersvan** [comment] 2017-09-14 10:58
@QaisarRajput don't be an alarmist, please always provide a reproducible example if you'd like to get help. I obviously can't reproduce your error without the code.

**Comment by QaisarRajput** [comment] 2017-09-14 11:10
Sorry! i have tensorflow 1.2.1 installed on ubuntu. with python 2.7.
i ran the notebook `wide_and_deep_export_r1.0_legacy.ipynb` and it successfully executed and i have the trained model stored. Then i ran the code suggested by you to make tf.Example. so that i can predict the model output on the given data. it also worked fine. but i didn't get the output in the following format when i printed the `serialized_proto_handle` object. as you suggested

> This serialized_proto_handle should look like this:
     
     [b'\n\xaa\x02\n\x1a\n\x0ehours_per_week\x12\x08\x12\x06\n\x04\x00\x00 B\n\x1d\n\x0crelationship\x12\r\n\x0b\n\tOwn-child\n\x19\n\reducation_num\x12\x08\x12\x06\n\x04\x00\x00\xe0@\n#\n\noccupation\x12\x15\n\x13\n\x11Machine-op-inspct\n\x18\n\x0ccapital_gain\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x18\n\x0ccapital_loss\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x15\n\teducation\x12\x08\n\x06\n\x0411th\n\x0f\n\x03age\x12\x08\x12\x06\n\x04\x00\x00\xc8A\n#\n\x0enative_country\x12\x11\n\x0f\n\rUnited-States\n\x18\n\tworkclass\x12\x0b\n\t\n\x07Private\n\x12\n\x06gender\x12\x08\n\x06\n\x04Male']

My output looks like when i do `print(serialized_proto_handle)` 

      <google.protobuf.pyext._message.RepeatedScalarContainer object at 0x7f9767d07490>

Am i doing something wrong here. ?

**Comment by QaisarRajput** [comment] 2017-09-14 11:13
I also ran the `saved_model_cli` command with the output you got on my trained model. it worked fine. So i think the problem must be in the tf.Example part. Model is fine

**Comment by MtDersvan** [comment] 2017-09-14 11:20
That is indeed strange.
The following code works for me for tf 1.3 on both Python 2 and 3.
```
import tensorflow as tf

def _float_feature(value):
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _bytes_feature(value):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

feature_dict = {'age': _float_feature(value=25),
                'capital_gain': _float_feature(value=0),
                'capital_loss': _float_feature(value=0),
                'education': _bytes_feature(value='11th'.encode()),
                'education_num': _float_feature(value=7),
                'gender': _bytes_feature(value='Male'.encode()),
                'hours_per_week': _float_feature(value=40),
                'native_country': _bytes_feature(value='United-States'.encode()),
                'occupation': _bytes_feature(value='Machine-op-inspct'.encode()),
                'relationship': _bytes_feature(value='Own-child'.encode()),
                'workclass': _bytes_feature(value='Private'.encode())}

example = tf.train.Example(features=tf.train.Features(feature=feature_dict))

serialized = example.SerializeToString()

serialized_proto = tf.contrib.util.make_tensor_proto(serialized, shape=[1])

serialized_proto_handle = serialized_proto.string_val
```

Make sure that you run exact same code that I specified.
If errors persist, print all the intermediate values (example, serialized, serialized_proto, serialized_proto_handle).

**Comment by QaisarRajput** [comment] 2017-09-14 11:32
I got it! i just had to print like `print(list(serialized_proto_handle))`. although the format is not same (order of dictionary keys which are actually get parsed into this format) but it works. Thanks!
for reference my output looks like this

     ['\n\xaa\x02\n\x18\n\x0ccapital_gain\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x19\n\reducation_num\x12\x08\x12\x06\n\x04\x00\x00\xe0@\n\x15\n\teducation\x12\x08\n\x06\n\x0411th\n\x12\n\x06gender\x12\x08\n\x06\n\x04Male\n\x18\n\tworkclass\x12\x0b\n\t\n\x07Private\n\x18\n\x0ccapital_loss\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x0f\n\x03age\x12\x08\x12\x06\n\x04\x00\x00\xc8A\n#\n\noccupation\x12\x15\n\x13\n\x11Machine-op-inspct\n\x1a\n\x0ehours_per_week\x12\x08\x12\x06\n\x04\x00\x00 B\n#\n\x0enative_country\x12\x11\n\x0f\n\rUnited-States\n\x1d\n\x0crelationship\x12\r\n\x0b\n\tOwn-child']

**Comment by MtDersvan** [comment] 2017-09-14 11:36
Great! This is probably a tensorflow 1.2 vs 1.3 difference as it is a `contrib` function.
Closing the issue as it has been resolved.
Feel free to reopen if needed.

**Closed by MtDersvan** 2017-09-14 11:36 UTC
